export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SHOW_AUTH_FORM = 'SHOW_AUTH_FORM';
export const HIDE_AUTH_FORM = 'HIDE_AUTH_FORM';
export const SHOW_REG_FORM = 'SHOW_REG_FORM';
export const HIDE_REG_FORM = 'HIDE_REG_FORM';
export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCEEDED = 'LOG_IN_SUCCEEDED';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const SAVE_TEST = 'SAVE_TEST';
export const UPDATE_TEST = 'UPDATE_TEST';
export const RESET_TEST = 'RESET_TEST';
export const ANSWER_TEST = 'ANSWER_TEST';
export const ANSWER_TEST_RESULT = 'ANSWER_TEST_RESULT';
export const SAVE_TEST_SUCCEEDED = 'SAVE_TEST_SUCCEEDED';
export const SAVE_TEST_FAILED = 'SAVE_TEST_FAILED';
export const SEARCH = 'SEARCH';

export const EDIT_FORM_OPEN = 'EDIT_FORM_OPEN';
export const EDIT_FORM_CLOSE = 'EDIT_FORM_CLOSE';

export const LOAD_TEST = 'LOAD_TEST';
export const LOAD_TEST_SUCCEEDED = 'LOAD_TEST_SUCCEEDED';
export const LOAD_TEST_FAILED = 'LOAD_TEST_FAILED';

export const GET_TEST_LIST = 'GET_TEST_LIST';
export const GET_TEST_LIST_SUCCEEDED = 'GET_TEST_LIST_SUCCEEDED';
export const GET_TEST_LIST_FAILED = 'GET_TEST_LIST_FAILED';

export const OPEN_FLASH_MESSAGE = 'OPEN_FLASH_MESSAGE';
export const CLOSE_FLASH_MESSAGE = 'CLOSE_FLASH_MESSAGE';
export const TOGGLE_FLASH_MESSAGE = 'TOGGLE_FLASH_MESSAGE';