export const SAVE_TEST = 'SAVE_TEST';
export const SAVE_TEST_SUCCEEDED = 'SAVE_TEST_SUCCEEDED';
export const SAVE_TEST_FAILED = 'SAVE_TEST_FAILED';

export const GET_TEST_LIST = 'GET_TEST_LIST';
export const GET_TEST_LIST_SUCCEEDED = 'GET_TEST_LIST_SUCCEEDED';
export const GET_TEST_LIST_FAILED = 'GET_TEST_LIST_FAILED';
